spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: Ab123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

---
server:
  port: 8080
spring:
  profiles: dev

---


